name: 'GitHub Actions news'

on:
  push:
    branches: 
    - main
    tags:
    - 'v$(date +%Y%m%d%H%M%S)'
  schedule:
  - cron: '1 0 * * *'
  - cron: '1 16 * * *'
jobs:
  Pic-spider:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: 'Install dependencies'
        run: python -m pip install --upgrade pip
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt
      - name: 'Working'
        env:
          KEY: ${{secrets.KEY}}
          TZ: 'Asia/Shanghai'
        timeout-minutes: 360
        run: bash ./main.sh
        - name: pull-request-action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          PULL_REQUEST_BRANCH: "master"
          BRANCH_PREFIX: "update/"
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "⌚️$(date +%Y%m%d%H%M%S)" -a
      - name: 'Push changes'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
      - name: 'Create a Release'
        uses: elgohr/Github-Release-Action@master
        env:
           GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
           args: news
